overrides:
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  diff@<8.0.3: '>=8.0.3'
  form-data@<2.5.4: '>=2.5.4'
  got@<11.8.5: '>=11.8.5'
  handlebars@<4.7.7: '>=4.7.7'
  marked@<4.0.10: '>=4.0.10'
  minimist@<0.2.1: '>=0.2.1'
  minimist@<0.2.4: '>=0.2.4'
  moment@<2.29.2: '>=2.29.2'
  moment@>=2.18.0 <2.29.4: '>=2.29.4'
  qs@<6.14.1: '>=6.14.1'
  tar@<=7.5.2: '>=7.5.3'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
